const initialFlightStrips = [
    {
        id: 'sva256',
        callsign: 'SVA256',
        operationType: 'DEPARTURE',
        status: 'DEP_QUEUE',

        aircraftType: 'B738',
        wakeCategory: 'M',
        equipment: 'L',
        beaconCode: '4251',

        departureAirport: 'RKSI',
        arrivalAirport: 'OEDF',
        route: 'DCT BOPTA Y711',
        altitude: 'FL350',
        requestedAltitude: 'FL350',

        runway: '35L',
        gate: 'G12',
        time: '1240',
        etd: '1240',
        clearance: 'CLRD',
        remarks: 'PDC',
    },
    {
        id: 'sva258',
        callsign: 'SVA258',
        operationType: 'DEPARTURE',
        status: 'PUSHBACK',

        aircraftType: 'A320',
        wakeCategory: 'M',
        equipment: 'L',
        beaconCode: '4253',

        departureAirport: 'RKSI',
        arrivalAirport: 'OEDF',
        route: 'DCT BOPTA Y711',
        altitude: 'FL330',
        requestedAltitude: 'FL330',

        runway: '34',
        gate: 'G08',
        time: '1250',
        etd: '1250',
        clearance: 'CLRD',
        remarks: 'PUSH',
    },
    {
        id: 'kal123',
        callsign: 'KAL123',
        operationType: 'DEPARTURE',
        status: 'TAXI_OUT',

        aircraftType: 'B772',
        wakeCategory: 'H',
        equipment: 'L',
        beaconCode: '4261',

        departureAirport: 'RKSI',
        arrivalAirport: 'KLAX',
        route: 'DCT GUKDO Y697',
        altitude: 'FL360',
        requestedAltitude: 'FL360',

        runway: '35R',
        gate: 'G21',
        time: '1305',
        etd: '1305',
        clearance: 'CLRD',
        remarks: 'TAXI',
    },
    {
        id: 'afa264',
        callsign: 'AFA264',
        operationType: 'DEPARTURE',
        status: 'LINE_UP',

        aircraftType: 'A359',
        wakeCategory: 'H',
        equipment: 'L',
        beaconCode: '4263',

        departureAirport: 'RKSI',
        arrivalAirport: 'LFPG',
        route: 'DCT BOPTA Y711',
        altitude: 'FL380',
        requestedAltitude: 'FL380',

        runway: '35L',
        gate: 'G15',
        time: '1310',
        etd: '1310',
        clearance: 'CLRD',
        remarks: 'LUAW',
    },
    {
        id: 'ces842',
        callsign: 'CES842',
        operationType: 'DEPARTURE',
        status: 'AIRBORNE',

        aircraftType: 'A321',
        wakeCategory: 'M',
        equipment: 'L',
        beaconCode: '4271',

        departureAirport: 'RKSI',
        arrivalAirport: 'ZSPD',
        route: 'DCT AGAVO Y644',
        altitude: 'FL310',
        requestedAltitude: 'FL310',

        runway: '35R',
        gate: 'G03',
        time: '1315',
        etd: '1315',
        clearance: 'CLRD',
        remarks: 'AIR',
    },

    {
        id: 'thy5ht',
        callsign: 'THY5HT',
        operationType: 'ARRIVAL',
        status: 'ARR_QUEUE',

        aircraftType: 'A321',
        wakeCategory: 'M',
        equipment: 'L',
        beaconCode: '4311',

        departureAirport: 'LTBA',
        arrivalAirport: 'RKSI',
        route: 'DCT GUKDO STAR',
        altitude: 'FL210',
        requestedAltitude: 'FL210',

        runway: '36',
        gate: 'A04',
        time: '1306',
        eta: '1306',
        clearance: 'ARR',
        remarks: 'SEQ',
    },
    {
        id: 'ana702',
        callsign: 'ANA702',
        operationType: 'ARRIVAL',
        status: 'APPROACH',

        aircraftType: 'B788',
        wakeCategory: 'H',
        equipment: 'L',
        beaconCode: '4313',

        departureAirport: 'RJTT',
        arrivalAirport: 'RKSI',
        route: 'DCT OLMEN STAR',
        altitude: '7000',
        requestedAltitude: '7000',

        runway: '34',
        gate: 'A12',
        time: '1312',
        eta: '1312',
        clearance: 'APP',
        remarks: 'ILS',
    },
    {
        id: 'dal158',
        callsign: 'DAL158',
        operationType: 'ARRIVAL',
        status: 'ARRIVAL',

        aircraftType: 'A332',
        wakeCategory: 'H',
        equipment: 'L',
        beaconCode: '4321',

        departureAirport: 'KJFK',
        arrivalAirport: 'RKSI',
        route: 'DCT OLMEN STAR',
        altitude: '3000',
        requestedAltitude: '3000',

        runway: '33L',
        gate: 'A18',
        time: '1318',
        eta: '1318',
        clearance: 'LNDG',
        remarks: 'LAND',
    },
    {
        id: 'cca123',
        callsign: 'CCA123',
        operationType: 'ARRIVAL',
        status: 'TAXI_IN',

        aircraftType: 'B77W',
        wakeCategory: 'H',
        equipment: 'L',
        beaconCode: '4323',

        departureAirport: 'ZBAA',
        arrivalAirport: 'RKSI',
        route: 'DCT GUKDO STAR',
        altitude: 'GND',
        requestedAltitude: 'GND',

        runway: '34',
        gate: 'A06',
        time: '1322',
        eta: '1322',
        clearance: 'TAXI',
        remarks: 'IN',
    },
    {
        id: 'ual892',
        callsign: 'UAL892',
        operationType: 'ARRIVAL',
        status: 'ON_BLOCK',

        aircraftType: 'B789',
        wakeCategory: 'H',
        equipment: 'L',
        beaconCode: '4331',

        departureAirport: 'KSFO',
        arrivalAirport: 'RKSI',
        route: 'DCT OLMEN STAR',
        altitude: 'GND',
        requestedAltitude: 'GND',

        runway: '33R',
        gate: 'A22',
        time: '1330',
        eta: '1330',
        clearance: 'BLOCK',
        remarks: 'ONB',
    },

    {
        id: 'jal72',
        callsign: 'JAL72',
        operationType: 'TRANSIT',
        status: 'TRN_QUEUE',

        aircraftType: 'B789',
        wakeCategory: 'H',
        equipment: 'L',
        beaconCode: '4411',

        departureAirport: 'RJFF',
        arrivalAirport: 'ZBAA',
        route: 'DCT A582 DCT',
        altitude: 'FL370',
        requestedAltitude: 'FL370',

        runway: '-',
        gate: '-',
        time: '1320',
        clearance: 'TRN',
        remarks: 'MON',
    },
    {
        id: 'csn352',
        callsign: 'CSN352',
        operationType: 'TRANSIT',
        status: 'ENTRY',

        aircraftType: 'A320',
        wakeCategory: 'M',
        equipment: 'L',
        beaconCode: '4413',

        departureAirport: 'RKPC',
        arrivalAirport: 'ZGGG',
        route: 'DCT Y722 DCT',
        altitude: 'FL290',
        requestedAltitude: 'FL290',

        runway: '-',
        gate: '-',
        time: '1328',
        clearance: 'ENT',
        remarks: 'ENTRY',
    },
    {
        id: 'aca61',
        callsign: 'ACA61',
        operationType: 'TRANSIT',
        status: 'PASSING',

        aircraftType: 'B789',
        wakeCategory: 'H',
        equipment: 'L',
        beaconCode: '4421',

        departureAirport: 'CYVR',
        arrivalAirport: 'VHHH',
        route: 'DCT A593 DCT',
        altitude: 'FL390',
        requestedAltitude: 'FL390',

        runway: '-',
        gate: '-',
        time: '1335',
        clearance: 'PASS',
        remarks: 'MON',
    },
    {
        id: 'swa888',
        callsign: 'SWA888',
        operationType: 'TRANSIT',
        status: 'EXIT',

        aircraftType: 'B738',
        wakeCategory: 'M',
        equipment: 'L',
        beaconCode: '4423',

        departureAirport: 'RJCC',
        arrivalAirport: 'ZGHA',
        route: 'DCT Y685 DCT',
        altitude: 'FL350',
        requestedAltitude: 'FL350',

        runway: '-',
        gate: '-',
        time: '1340',
        clearance: 'EXIT',
        remarks: 'XFER',
    },

    {
        id: 'hl1234',
        callsign: 'HL1234',
        operationType: 'CIRCUIT',
        status: 'CCT_QUEUE',

        aircraftType: 'C172',
        wakeCategory: 'L',
        equipment: 'G',
        beaconCode: '4501',

        departureAirport: 'RKSI',
        arrivalAirport: 'RKSI',
        route: 'LOCAL PATTERN',
        altitude: '1000',
        requestedAltitude: '1000',

        runway: '35L',
        gate: 'GA',
        time: '1325',
        clearance: 'CCT',
        remarks: 'QUEUE',
    },
    {
        id: 'hl5678',
        callsign: 'HL5678',
        operationType: 'CIRCUIT',
        status: 'UPWIND',

        aircraftType: 'C172',
        wakeCategory: 'L',
        equipment: 'G',
        beaconCode: '4503',

        departureAirport: 'RKSI',
        arrivalAirport: 'RKSI',
        route: 'LOCAL PATTERN',
        altitude: '1000',
        requestedAltitude: '1000',

        runway: '35L',
        gate: 'GA',
        time: '1327',
        clearance: 'CCT',
        remarks: 'UPWND',
    },
    {
        id: 'hl9012',
        callsign: 'HL9012',
        operationType: 'CIRCUIT',
        status: 'CROSSWIND',

        aircraftType: 'C172',
        wakeCategory: 'L',
        equipment: 'G',
        beaconCode: '4511',

        departureAirport: 'RKSI',
        arrivalAirport: 'RKSI',
        route: 'LOCAL PATTERN',
        altitude: '1000',
        requestedAltitude: '1000',

        runway: '35L',
        gate: 'GA',
        time: '1329',
        clearance: 'CCT',
        remarks: 'XWIND',
    },
    {
        id: 'hl3456',
        callsign: 'HL3456',
        operationType: 'CIRCUIT',
        status: 'DOWNWIND',

        aircraftType: 'C172',
        wakeCategory: 'L',
        equipment: 'G',
        beaconCode: '4513',

        departureAirport: 'RKSI',
        arrivalAirport: 'RKSI',
        route: 'LOCAL PATTERN',
        altitude: '1000',
        requestedAltitude: '1000',

        runway: '35L',
        gate: 'GA',
        time: '1331',
        clearance: 'CCT',
        remarks: 'DWIND',
    },
    {
        id: 'hl7890',
        callsign: 'HL7890',
        operationType: 'CIRCUIT',
        status: 'BASE',

        aircraftType: 'C172',
        wakeCategory: 'L',
        equipment: 'G',
        beaconCode: '4521',

        departureAirport: 'RKSI',
        arrivalAirport: 'RKSI',
        route: 'LOCAL PATTERN',
        altitude: '1000',
        requestedAltitude: '1000',

        runway: '35L',
        gate: 'GA',
        time: '1333',
        clearance: 'CCT',
        remarks: 'BASE',
    },
    {
        id: 'hl2468',
        callsign: 'HL2468',
        operationType: 'CIRCUIT',
        status: 'FINAL',

        aircraftType: 'C172',
        wakeCategory: 'L',
        equipment: 'G',
        beaconCode: '4523',

        departureAirport: 'RKSI',
        arrivalAirport: 'RKSI',
        route: 'LOCAL PATTERN',
        altitude: '1000',
        requestedAltitude: '1000',

        runway: '35L',
        gate: 'GA',
        time: '1335',
        clearance: 'CCT',
        remarks: 'FINAL',
    },
];

export default initialFlightStrips;